name: Build and Run Docker Image (Success)

on:
  push:
    branches: [ "main" ]

jobs:
  build-and-run:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker
        uses: docker/setup-buildx-action@v3

      - name: Build Docker image
        run: docker build -t codefactory-devops-pratica-web .

      - name: Run container
        run: docker run -d -p 5000:5000 codefactory-devops-pratica-web

      - name: Test endpoint
        run: |
          sleep 5
          curl --fail http://localhost:5000/
